version: "3.9"

networks:
    laravel:
        name: laravel

services:
    app:
        container_name: laravel-app
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        container_name: laravel-mysql
        image: mysql:8.0
        restart: always
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
            - MYSQL_ROOT_PASSWORD=admin
        ports:
            - "3306:3306"
        networks:
            - laravel

    web:
        container_name: laravel-web
        image: nginx:stable-alpine
        restart: always
        ports:
            - "8100:80"
        volumes:
            - .:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    phpmyadmin:
        container_name: laravel-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8101:80"
        depends_on:
            - mysql
        links:
            - "mysql:db"
        networks:
            - laravel
